config/routes.rb
Rails.application.routes.draw do
  root 'landing#landing'
  devise_for :users
  resources :authorships, only: [:show]
  resources :usercreatedbills
  resources :bills
  get '/get_bills', to: 'bills#get_bills'

end

app/models/usercreatedbill.rb
# UserBill/user_bill might be a little easier to read and write. see also comment in bills controller
class Usercreatedbill < ActiveRecord::Base
  has_many :authorships
  has_many :users, through: :authorships

  # add validations here
end

app/controllers/user_created_bill_controller.rb
class UserCreatedBillsController < ApplicationController
  before_action :set_user_created_bill, only: [:show, :edit, :update, :destroy, :new]

  def index
    @user_created_bills = UserCreatedBill.all
  end
  def edit
  end
  def show
    redirect_to user_created_bills_path
  end
  def new
    @user_created_bill = UserCreatedBill.new
  end
  def create
    @user_created_bill = Bill.new(user_created_bill_params)

    respond_to do |format|
      if @user_created_bill.save
        format.html { redirect_to @user_created_bill, notice: 'Bill was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  def update
    respond_to do |format|
      if @user_created_bill.update(user_created_bill_params)
        format.html { redirect_to @user_created_bill, notice: 'Bill was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
  def destroy
    @user_created_bill.destroy
    respond_to do |format|
      format.html { redirect_to user_created_bills_url, notice: 'Bill was successfully destroyed.' }
    end
  end
  private
  def set_user_created_bill
    @user_created_bill = UserCreatedBill.all
  end

  def bill_params
      params.require(:user_created_bill).permit(:title, :kind, :content, :sponsor)
  end
end

app/controllers/usercreatedbills_controller.rb
class UsercreatedbillsController < ApplicationController
  # before_action :set_usercreatedbill, only: [:show, :edit, :update, :destroy, :new]
  before_action :authenticate_user!
  
  def index
    @usercreatedbills = Usercreatedbill.all
  end

  def edit
      @usercreatedbill = Usercreatedbill.find(params[:id])
  end

  def show
    @usercreatedbill = Usercreatedbill.find(params[:id])
  end

  def new
    @usercreatedbill = Usercreatedbill.new
  end

  def create
    @usercreatedbill = Usercreatedbill.new(usercreatedbill_params)

    respond_to do |format|
      if @usercreatedbill.save
        format.html { redirect_to @usercreatedbill, notice: 'Bill was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @usercreatedbill = Usercreatedbill.find(params[:id])
    respond_to do |format|
      if @usercreatedbill.update(usercreatedbill_params)
        format.html { redirect_to @usercreatedbill, notice: 'Bill was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
  def destroy
    @usercreatedbill = Usercreatedbill.find(params[:id])
    @usercreatedbill.destroy
    respond_to do |format|
      format.html { redirect_to usercreatedbills_url, notice: 'Bill was successfully destroyed.' }
    end
  end
  private
  # def set_usercreatedbill
  #   @usercreatedbill = UserCreatedBill.all
  # end

  def usercreatedbill_params
      params.require(:usercreatedbill).permit(:title, :kind, :content, :sponsor)
  end
end

app/views/usercreatedbills/_form.html.erb
<%= form_for(@usercreatedbill) do |f| %>
  <% if @usercreatedbill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usercreatedbill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @usercreatedbill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :sponsor %><br>
    <%= f.text_area :sponsor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usercreatedbills/_from.html.erb
<%= form_for(@user_created_bill) do |f| %>
  <% if @user_created_bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_created_bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @user_created_bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :sponsor %><br>
    <%= f.text_area :sponsor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usercreatedbills/edit.html.erb
<h1>Edit Bill</h1>

<%= render 'form' %>

<%= link_to 'Back', usercreatedbill_path %>

app/views/usercreatedbills/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Your Bills</h1>

<table>
  <thead>
    <tr>
      <!-- Add white space after each header -->
      <th>Title</th>
      <th>Type</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usercreatedbills.each do |bill| %>
      <tr>
        <td><%= link_to bill.title, usercreatedbill_path(bill) %></td>
        <td><%= bill.kind %></td>
        <td><%= bill.content %></td>
        <!-- add whitespace before & after each (CR)UD here action  -->
        <td><%= link_to 'Edit', edit_usercreatedbill_path(bill) %></td>
        <td><%= link_to 'Destroy', usercreatedbill_path(bill), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Bill', new_usercreatedbill_path %>

app/views/usercreatedbills/new.html.erb
<h1>New Bill</h1>

<%= render 'form' %>

<%= link_to 'Back', usercreatedbills_path %>

app/views/usercreatedbills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @usercreatedbill.title %>
</p>

<p>
  <strong>Type:</strong>
  <%= @usercreatedbill.kind %>
</p>

<p>
  <strong>Content:</strong>
  <%= @usercreatedbill.content %>
</p>

<%= link_to 'Edit', edit_usercreatedbill_path(@usercreatedbill) %> |
<%= link_to 'Back', usercreatedbills_path %>